/*Write a program which will draw the histogram for n integers from 0 to 99.  N is input by
the user.  Each of the n numbers will be generated by calling rand() % 100.  The program
will consist of two functions
(i) to collect the frequency distribution of the numbers
(ii) to print the histogram.  

An example histogram is shown here.
0 – 9 |*********************
10 – 19 |************
20 – 29 |*************
30 – 39 |**
......
90 – 99 |***************
*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#define SIZE 100

void generate(int n, int ar[SIZE]);
void collectFreq(int n, int ar[SIZE], int freq[10]);
void printOutput(int freq[10]);

int main()
{
    while(1){
    srand ( time(NULL) );
    int n;
    int ar[SIZE];
    int freq[10];
    printf("Please input N: \n");
    scanf("%d", &n);
    generate(n, ar);
    collectFreq(n, ar, freq);
    printOutput(freq);
    }
}

void generate(int n, int ar[SIZE])
{
    int i;
    for (i = 0; i < n; i++)
    {
        ar[i] = rand() % 100;
    }
}

void collectFreq(int n, int ar[SIZE], int freq[10])
{
    int i;

    int *ptr;

    ptr = &ar[0];

    for (i = 0; i < 10; i++) //clear the frequency array
        freq[i] = 0;

    for (i = 0; i < n; i++)
    {
        if (0 <= *ptr && *ptr < 10)
            freq[0]++;
        else if (10 <= *ptr && *ptr < 20)
            freq[1]++;
        else if (20 <= *ptr && *ptr < 30)
            freq[2]++;
        else if (30 <= *ptr && *ptr < 40)
            freq[3]++;
        else if (40 <= *ptr && *ptr < 50)
            freq[4]++;
        else if (50 <= *ptr && *ptr < 60)
            freq[5]++;
        else if (60 <= *ptr && *ptr < 70)
            freq[6]++;
        else if (70 <= *ptr && *ptr < 80)
            freq[7]++;
        else if (80 <= *ptr && *ptr < 90)
            freq[8]++;
        else if (90 <= *ptr && *ptr < 100)
            freq[9]++;
        else
            printf("ERROR");
        ptr++;
    }
}
void printOutput(int freq[10])
{
    int i;
    int j;

    for(j=0; j<10; j++)
    {
        printf("%d-%d\t|",j*10, j*10+9);
        for (i = 0; i < freq[j]; i++)
        printf("*");
    putchar('\n');
    }
}
